/**
 * @sb/shared — 前后端契约单一事实源。
 *
 * 原则（规划 §4.1）：SSE 事件 / 内容块协议 / REST 类型 / 领域模型全部在此定义，
 * server 与 web 只引用不复制——根治 v1 前后端类型双写漂移。
 */
export * from './sse-events.js';
export * from './content-blocks.js';
export * from './quiz-source.js';
export * from './quiz-tier.js';
export * from './choice.js';
export * from './answer-style.js';
export * from './doc-rag.js';
export * from './api.js';
export * from './domain.js';
export * from './pk.js';
export * from './task-list.js';
export * from './memory.js';
export * from './scenario.js';
export * from './auth.js';
export * from './ebbinghaus.js';
export * from './fsrs.js';
export * from './learner.js';
export * from './term-graph.js';
export * from './adaptive.js';
export * from './review-goal.js';
export * from './continent.js';
export * from './continent-expand.js';
export * from './continent-wild.js';
export * from './continent-upkeep.js';
export * from './drill.js';
export * from './reader-doc.js';
export * from './lookup.js';
export * from './guide.js';
export * from './typing.js';
export * from './sources.js';
export * from './video-route.js';
export * from './ai-ops.js';
export * from './npc.js';
export * from './npc-life.js';
export * from './term-highlight.js';
export * from './coach.js';
export * from './pomodoro.js';
export * from './term-cards.js';
export * from './chest-pool.js';
export * from './tool-ecosystem.js';
export * from './fts.js';
export * from './chat-limits.js';
export * from './speech.js';
export * from './follow-up.js';
export * from './platform-quota.js';
export * from './platform-channel.js';
export * from './demo-content.js';
export * from './quiz-explanation.js';
export * from './quiz-attempts.js';
export * from './spell-chant.js';
export * from './spell-kinds.js';
export * from './fsrs-fit.js';
export * from './exam-scope.js';
export * from './exam-sources.js';
